apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  selector:
    pod: node-app
    tier: backend
  type: LoadBalancer
  ports:
  - name:  default
    port:  80
    protocol: 'TCP'
    targetPort: 80